/*
 * build_id.h - Auto-generated build identification
 * Generated: 2025-09-09T10:07:44Z
 * 
 * IMPORTANT: This file is auto-generated by scripts/generate_build_id.sh
 * Do not edit manually - changes will be overwritten on next build
 */

#ifndef BUILD_ID_H
#define BUILD_ID_H

// Build identification
#define BUILD_GIT_SHA       "901dbd1-dirty"
#define BUILD_GIT_BRANCH    "master"
#define BUILD_UTC_TIME      "2025-09-09T10:07:44Z"
#define BUILD_UNIX_TIME     1757412464UL

// Combined build identifier for ready token
#define BUILD_ID_STRING     BUILD_GIT_SHA " " BUILD_UTC_TIME

// Ready token format: READY <board> <git_sha> <utc_timestamp>
#define READY_TOKEN_FORMAT  "READY %s %s %s\r\n"

#endif // BUILD_ID_H
