#!/bin/bash
#
# Generate build_id.h header with git SHA + UTC timestamp
# Usage: ./scripts/generate_build_id.sh <target_directory>
#

set -euo pipefail

# Check arguments
if [ $# -lt 1 ]; then
    echo "Build ID Header Generation"
    echo "Usage: $0 <target_directory>"
    echo
    echo "Examples:"
    echo "  $0 HIL_RTT_Test"
    echo "  $0 ."
    echo
    echo "Generates build_id.h with git SHA and UTC timestamp"
    exit 1
fi

TARGET_DIR="$1"

# Validate target directory
if [ ! -d "$TARGET_DIR" ]; then
    echo "Error: Target directory not found: $TARGET_DIR"
    exit 1
fi

# Get git information
if git rev-parse --git-dir > /dev/null 2>&1; then
    GIT_SHA=$(git rev-parse --short HEAD)
    GIT_BRANCH=$(git branch --show-current 2>/dev/null || echo "detached")
    GIT_DIRTY=""
    if ! git diff-index --quiet HEAD 2>/dev/null; then
        GIT_DIRTY="-dirty"
    fi
else
    GIT_SHA="unknown"
    GIT_BRANCH="unknown"
    GIT_DIRTY=""
fi

# Generate UTC timestamp
UTC_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
UNIX_TIMESTAMP=$(date +%s)

# Create build_id.h header
BUILD_ID_HEADER="$TARGET_DIR/build_id.h"

cat > "$BUILD_ID_HEADER" << EOF
/*
 * build_id.h - Auto-generated build identification
 * Generated: $UTC_TIMESTAMP
 * 
 * IMPORTANT: This file is auto-generated by scripts/generate_build_id.sh
 * Do not edit manually - changes will be overwritten on next build
 */

#ifndef BUILD_ID_H
#define BUILD_ID_H

// Build identification
#define BUILD_GIT_SHA       "$GIT_SHA$GIT_DIRTY"
#define BUILD_GIT_BRANCH    "$GIT_BRANCH"
#define BUILD_UTC_TIME      "$UTC_TIMESTAMP"
#define BUILD_UNIX_TIME     ${UNIX_TIMESTAMP}UL

// Combined build identifier for ready token
#define BUILD_ID_STRING     BUILD_GIT_SHA " " BUILD_UTC_TIME

// Ready token format: READY <board> <git_sha> <utc_timestamp>
#define READY_TOKEN_FORMAT  "READY %s %s %s\\r\\n"

#endif // BUILD_ID_H
EOF

echo "✓ Generated build ID header: $BUILD_ID_HEADER"
echo "  Git SHA: $GIT_SHA$GIT_DIRTY"
echo "  Branch: $GIT_BRANCH" 
echo "  UTC Time: $UTC_TIMESTAMP"
echo "  Unix Time: $UNIX_TIMESTAMP"